"""empty message

Revision ID: 4826cfd56873
Revises: 0ad2308c0437
Create Date: 2019-04-27 15:15:05.038941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4826cfd56873'
down_revision = '0ad2308c0437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cepage', sa.Column('superficie_france', sa.Integer(), nullable=True))
    op.add_column('cepage', sa.Column('superficie_monde', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cepage', 'superficie_monde')
    op.drop_column('cepage', 'superficie_france')
    # ### end Alembic commands ###
