"""empty message

Revision ID: c7074277067a
Revises: 4826cfd56873
Create Date: 2019-04-30 10:17:47.298794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7074277067a'
down_revision = '4826cfd56873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cepage', sa.Column('vignobles', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cepage', 'vignobles')
    # ### end Alembic commands ###
